# This file was generated by GoReleaser. DO NOT EDIT.
cask "git-get" do
  name "git-get"
  desc "Tool to clone/fetch project repositories an-mass using Gitfile configuration file. git-get can also generate Gitfile from github, gitlab or bitbucket, to have all repositories user has access to."
  homepage "https://github.com/isindir/git-get"
  version "0.0.36"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "git-get"

  on_macos do
    on_intel do
      url "https://github.com/isindir/git-get/releases/download/v#{version}/git-get_Darwin_x86_64.tar.gz",
        verified: "github.com/isindir/git-get"
      sha256 "0c0c7a7f24b9ca5a395f1477d94fe513a60ff1054b3552753ac3b37d13767909"
    end
    on_arm do
      url "https://github.com/isindir/git-get/releases/download/v#{version}/git-get_Darwin_arm64.tar.gz",
        verified: "github.com/isindir/git-get"
      sha256 "207199c7c80c3462af05d0d107b732d4f0c2c1668919b1a548adb97f901445cd"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/isindir/git-get/releases/download/v#{version}/git-get_Linux_x86_64.tar.gz",
        verified: "github.com/isindir/git-get"
      sha256 "96ed07823cd75f16533c6d059e7f87cff26b147816d7ea8e8b731bbc104c67cf"
    end
    on_arm do
      url "https://github.com/isindir/git-get/releases/download/v#{version}/git-get_Linux_arm64.tar.gz",
        verified: "github.com/isindir/git-get"
      sha256 "308932ffcdafd8ed28121cba6c4a5473d27d58dad8d9a090de4f6d15a488258c"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/git-get"]
    end
  end

  # No zap stanza required
end
