# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitGet < Formula
  desc "Tool to clone/fetch project repositories an-mass using Gitfile configuration file. git-get can also generate Gitfile from github, gitlab or bitbucket, to have all repositories user has access to."
  homepage "https://github.com/isindir/git-get"
  version "0.0.22"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/isindir/git-get/releases/download/v0.0.22/git-get_Darwin_x86_64.tar.gz"
      sha256 "24afc806ccda03af9d934a8084bc934cca50b3ca9b91a1d021c3fd6f142d329a"

      def install
        bin.install "git-get"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/isindir/git-get/releases/download/v0.0.22/git-get_Darwin_arm64.tar.gz"
      sha256 "57cd3c205f0db0da7bdf92779a0af1505cf8aaca8fb3c98e6b2cba430fcee9ee"

      def install
        bin.install "git-get"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/isindir/git-get/releases/download/v0.0.22/git-get_Linux_x86_64.tar.gz"
      sha256 "b00da64740c2eab7ac9405387275d64e299d6d7d0eb034938812da5617ec7e56"

      def install
        bin.install "git-get"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/isindir/git-get/releases/download/v0.0.22/git-get_Linux_arm64.tar.gz"
      sha256 "d494f4600873ffc1e5ecbf816857084aeb401330d3234af8508e400be60398f6"

      def install
        bin.install "git-get"
      end
    end
  end

  test do
    system "#{bin}/git-get", "version", "--long"
  end
end
